'use client';
import {useEffect,useState} from 'react';
export default function Admin(){const [authed,setAuthed]=useState(null),[password,setPassword]=useState(''),[rows,setRows]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 async function load(){const r=await fetch('/api/admin/attendees');if(r.ok){const j=await r.json();setRows(j.data||[]);setAuthed(true)}else setAuthed(false)}
 useEffect(()=>{load()},[]);
 async function login(e){e.preventDefault();setLoading(true);setError('');const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok){setError('Incorrect admin password.');setLoading(false);return}setPassword('');await load();setLoading(false)}
 async function logout(){await fetch('/api/admin/logout',{method:'POST'});setAuthed(false)}
 async function remove(id){if(!confirm('Delete this RSVP?'))return;await fetch('/api/admin/attendees',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});load()}
 function csv(){const head=['Date','Attendance','Guest Count','Names','Phone','Message'];const lines=[head,...rows.map(r=>[new Date(r.created_at).toLocaleString(),r.attending,r.guest_count,r.guest_names,r.phone||'',r.message||''])].map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','));const blob=new Blob([lines.join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='joseph-juliet-rsvps.csv';a.click();URL.revokeObjectURL(url)}
 if(authed===null)return <div className="login"><div className="login-card"><h1>Joseph <span className="gold">&</span> Juliet</h1><p style={{textAlign:'center',color:'#aaa'}}>Loading admin panel…</p></div></div>;
 if(!authed)return <div className="login"><form className="login-card" onSubmit={login}><div className="eyebrow" style={{textAlign:'center'}}>Private RSVP dashboard</div><h1>Admin <span className="gold">Login</span></h1><div className="field"><label>Admin password</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus/></div>{error&&<p className="error">{error}</p>}<button className="submit" disabled={loading}>{loading?'Signing in…':'Enter dashboard'}</button></form></div>;
 const yes=rows.filter(r=>r.attending==='Yes');const no=rows.filter(r=>r.attending==='No');const maybe=rows.filter(r=>r.attending==='Maybe');const guests=yes.reduce((n,r)=>n+Number(r.guest_count||0),0);
 return <main className="admin"><div className="admin-wrap"><header className="admin-head"><div><div className="eyebrow gold">21 December 2026 • Munondo 11 Events</div><h1>RSVP Dashboard</h1><p>Joseph & Juliet — guest responses</p></div><div><button className="btn" onClick={csv}>Export CSV</button> <button className="btn dark" onClick={logout}>Logout</button></div></header>
 <div className="stats"><div className="stat"><span>Responses</span><strong>{rows.length}</strong></div><div className="stat"><span>Attending</span><strong>{yes.length}</strong></div><div className="stat"><span>Guests</span><strong>{guests}</strong></div><div className="stat"><span>Maybe / No</span><strong>{maybe.length} / {no.length}</strong></div></div>
 <div className="table-wrap"><table className="table"><thead><tr><th>Received</th><th>Status</th><th>Guests</th><th>Names</th><th>Phone</th><th>Message</th><th></th></tr></thead><tbody>{rows.length===0?<tr><td colSpan="7" style={{color:'#aaa'}}>No RSVPs yet.</td></tr>:rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td><span className="pill">{r.attending}</span></td><td>{r.guest_count}</td><td style={{whiteSpace:'pre-wrap'}}>{r.guest_names}</td><td>{r.phone||'—'}</td><td>{r.message||'—'}</td><td><button className="btn dark" onClick={()=>remove(r.id)}>Delete</button></td></tr>)}</tbody></table></div></div></main>
}
